### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by vincecarterhu** [JessYanCoding/AndroidAutoSize#104]
- [x] Autosize Version: v1.1.0
- [x] Target Android Version: Android 8.0
- [x] Device Model: 魅蓝note5
- [x] Device Resolution: 1080px * 1920px
- [x] Design Size On AndroidManifest:  369dp * 656dp -->

### Log:
 java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/FragmentManager$FragmentLifecycleCallbacks;
        at me.jessyan.autosize.AutoSizeConfig.init(AutoSizeConfig.java:215)
        at me.jessyan.autosize.AutoSizeConfig.init(AutoSizeConfig.java:153)
        at me.jessyan.autosize.InitProvider.onCreate(InitProvider.java:37)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1847)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1822)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6129)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5699)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5635)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6406)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)

**Comment by JessYanCoding** [comment]
support v7 版本号是多少

**Comment by vincecarterhu** [comment]
> support v7 版本号是多少

27.1.0

**Comment by JessYanCoding** [comment]
升到 28.0.0，看看官方 Demo，是否可以运行，实在不行就用 v0.6.0

**Comment by vincecarterhu** [comment]
v0.6.0是OK的

**Comment by JessYanCoding** [comment]
https://www.cnblogs.com/fomin/p/8426479.html

**Comment by JessYanCoding** [comment]
就是 support 库冲突的问题，按照上面的教程用 gradlew 命令看看依赖信息，将版本统一
