### ISSUE TITLE
JessYan: 意见收集 😘，请进 QQ 群: 455850365

### ISSUE THREAD

**Issue by JessYanCoding** [JessYanCoding/AndroidAutoSize#118]
* 有什么问题可以直接进 [ ![QQ-Group](https://img.shields.io/badge/QQ%E7%BE%A4-455850365%20%7C%20301733278-orange.svg?style=flat-square) ](https://shang.qq.com/wpa/qunwpa?idkey=7e59e59145e6c7c68932ace10f52790636451f01d1ecadb6a652b1df234df753) 咨询

**如果您对 **AndroidAutoSize** 和 **JessYan** 有什么好的建议，都可以在下面留言以及讨论**

**Comment by JessYanCoding** [comment]
@liaohuyu https://github.com/JessYanCoding/AndroidAutoSize/issues/116

**Comment by manondidi** [comment]
> @Leu-Z wrap_content 是按图片的实际大小来显示，在小屏显示正常，在大屏显示效果就很小不是很正常吗，因为图片实际大小是没变的，你要想这个图片也能和其他控件一样同比例放大，就给它标注尺寸，使用 wrap_content 框架是不会帮你同比例缩放的

您说的是 这个框架 wrap_content 是不会帮忙做适配的, 只有写死固定的值 比如 100dp 框架才会做适配吗
比如说我的 imageview  textView 如果是wrap_content 宽高是没用的
如果是textview 只帮我们处理 字体大小的放大缩小适配 从而达到 textview的放大缩小适配
而imageview是无法处理的

**Comment by chenkezhao** [comment]
使用bugly的热更新代码后，AndroidAutoSize 失效，布局比例无法转换。能支持bugly热更新最好了！

**Comment by JessYanCoding** [comment]
@chenkezhao 可能是多进程问题，https://github.com/JessYanCoding/AndroidAutoSize/issues/13#9

**Comment by Maxitk** [comment]
大神，我重新提问一下，我在第一个页面（SplashActivity）初始化了一些东西，接着跳入MainActivity，当我启动的时候，马上熄屏，接着再解锁，图标及其他layout全部变形了（包括非自定义控件），我在mainactivity和splashactivity都有重写getResources的方法

**Comment by primerToforget** [comment]
大神，我在自己的工程使用了您的适配方案，然后项目某个模块要拆分给兄弟部门使用，但是他们的适配方案不同，如何不影响兄弟部门的主工程，仅适配自己的moudle。moudle我是通过nexus打包的。

**Comment by tydqcjj** [comment]
如何对高进行适配。这是我的配置
`        <meta-data
            android:name="design_width_in_dp"
            android:value="640" />
        <meta-data
            android:name="design_height_in_dp"
            android:value="360" />`
我设置一个控件的
`android:layout_width="640dp"
        android:layout_height="360dp"`
这个时候控件的宽占满整个屏幕，但是高却没有占满屏幕。
如果我想让设计图完全按比例映射到屏幕上，应该怎么做？

**Comment by JessYanCoding** [comment]
@tydqcjj [为什么说 AndroidAutoLayout 的设计有问题？](https://mp.weixin.qq.com/s/SDHL26XgIjjlK-RLd_SSCw)

**Comment by tydqcjj** [comment]
> @tydqcjj 做不到，不是所有设备的屏幕高宽比都和你的设计图一样，除非你想让你的 View 变形，[为什么说 AndroidAutoLayout 的设计有问题？](https://mp.weixin.qq.com/s/SDHL26XgIjjlK-RLd_SSCw)

能否做到自由切换适配方案。比如说有些activity需要适配宽，有些activity需要适配高，有些需要宽和高同时适配哪怕view变形也行。然后通过一个接口去自定义。

**Comment by JessYanCoding** [comment]
@tydqcjj 单独适配宽和单独适配高是本框架的基础功能，自己看看文档和 Demo 里面有用法，想同时适配宽和高，建议使用 AndroidAutoLayout，本框架不会支持这种会导致 View 变形的需求

**Comment by liaohuyu** [comment]
@JessYanCoding  适配dialog   是需要每次show之前都调用AutoSize#autoConvertDensity() ？
在fragment   onResume也调用下这个才能完全适配么?    我在getResources已经调用了AutoSizeCompat.autoConvertDensityOfGlobal((super.getResources()))；。发现dialog有时候在回调页面的时候会适配失效。我也认真看了13的总结。只是想再确认一下，是否这样做就能完全适配dialog和fragment了

**Comment by liaohuyu** [comment]
@JessYanCoding 还有个问题就是在getResources() 这个方法被调用太多次了，特别是有列表的页面，不停被调用   这样会不会影响性能？

**Comment by JessYanCoding** [comment]
@liaohuyu 最终解决方案就是利用 getResources() 会被调用多次的原理，以增加 density 的稳定性，并且 v1.1.2 已经优化了适配时的性能，所以你考虑的问题已经最大限度的优化了，我都是用上千次的调用测试的，也就几十微秒。

**Comment by FOnlyJack** [comment]
这句话如果没有特殊要求 AutoSizeConfig.getInstance()
                .setBaseOnWidth(true)  用设置吗？？？

**Comment by JessYanCoding** [comment]
@FOnlyJack 不用，默认为 true

**Comment by 656025633** [comment]
您好 ，使用您的适配框架过程中 在使用dialog或者popwindow都会出现偏移的问题，dialog一直靠右对齐，请问有解决方案么？

**Comment by zb666** [comment]
您好，项目中有个"App 字体大小"不随着手机系统变化而变化的功能，我参照了网上的一些方案，在BaseActivity中复写getResources方法，还原系统字体大小，但是这样一来导致了AutoSize适配无效。想请教下解决的方案

**Comment by JessYanCoding** [comment]
@656025633 翻之前的 issues

**Comment by MrFuShuai** [comment]
使用 AutoSize做屏幕适配后, Activity一段时间后会执行自动 stop(方法),查看log 显示 AndroidAutoSize: initScaledDensity = 3.0 on ConfigurationChanged,导致程序退出,请问这个问题是否遇到过,是不是我的某项配置有问题? 谢谢!

**Comment by JessYanCoding** [comment]
@MrFuShuai 框架自动执行 stop 方法，是不可能的，框架自身就没调用过 stop 方法，这个方法是提供给开发者使用的，而且还必须传入当前 Activity，程序退出是什么意思？是奔溃，奔溃的 Exception 是什么，原因是什么？这些不提供没法给出答案

**Comment by TianGuisen** [comment]
预览那里没法选择自创的模拟器啊。android studio3.5,记得以前版本可以来着，咋整

**Comment by CoolChimpanzee** [comment]
如果以宽度为基准，那么高度如何做到跟设计图一样呢，我在小米5x手机上获得屏幕宽高是是标准的360x640dp ,然后我设置以宽在布局中的空间高度600dp还是填充漫屏幕的，求指教

**Comment by JessYanCoding** [comment]
@CoolChimpanzee 答案是，当以宽为基准是，没法做到高度纵向拉伸填充满屏幕和设计图一样，当以高度为基准时，则宽度也没法做到，如果可以实现以上需求的话，那何必还多增加一个条件变量，让你区分是以宽或者以高为基准呢，https://mp.weixin.qq.com/s/SDHL26XgIjjlK-RLd_SSCw

**Comment by quzhongrensan** [comment]
我测试在小米mix2上，以高度为基准也不能占满屏幕高度，

**Comment by yyc2413** [comment]
setPrivateFontScale使用后如何刷新呢，目前需要重启app才能刷新字体大小

**Comment by loyilin** [comment]
华为平板启动activity闪退

java.lang.IllegalArgumentException: lightY must be finite, given=NaN
        at android.graphics.HardwareRenderer.validateFinite(HardwareRenderer.java:855)
        at android.graphics.HardwareRenderer.setLightSourceGeometry(HardwareRenderer.java:227)
        at android.view.ThreadedRenderer.setLightCenter(ThreadedRenderer.java:510)
        at android.view.ThreadedRenderer.setup(ThreadedRenderer.java:496)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2748)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1879)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8170)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
        at android.view.Choreographer.doCallbacks(Choreographer.java:875)
        at android.view.Choreographer.doFrame(Choreographer.java:776)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by loyilin** [comment]
找不到资源id闪退

Caused by: android.content.res.Resources$NotFoundException: Drawable com.amigaga.gagabot:drawable/edit_text_background with resource ID #0x7f0600e7
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/edit_text_background.xml from drawable resource ID #0x7f0600e7

**Comment by loyilin** [comment]
注释掉使用的代码，其他ID又报错，没法用

**Comment by JessYanCoding** [comment]
@yyc2413 重建所有Activity，或调用一次 [setDensity](https://github.com/JessYanCoding/AndroidAutoSize/blob/e402ecdd99/autosize/src/main/java/me/jessyan/autosize/AutoSize.java#L176) 后重绘所有用到字体的 View

**Comment by HysonHou** [comment]
> 使用 AutoSize做屏幕适配后, Activity一段时间后会执行自动 stop(方法),查看log 显示 AndroidAutoSize: initScaledDensity = 3.0 on ConfigurationChanged,导致程序退出,请问这个问题是否遇到过,是不是我的某项配置有问题? 谢谢!

我也遇到类似的情况了，请问是怎么解决的

**Comment by zb666** [comment]
你好，邮件已经收到，谢谢
