### ISSUE TITLE
关于屏幕适配AutoSize.autoConvertDensityOfGlobal(this)

### ISSUE THREAD

**Issue by Gseve** [JessYanCoding/AndroidAutoSize#120]
在 
@Override
    public Resources getResources() {
        AutoSize.autoConvertDensityOfGlobal(this);
        return super.getResources();
    }
小米手机(小米3--android4.4.4和小米8--android9.0)上直接anr或者崩溃
2019-01-07 17:17:50.017 4072-4072/? E/AndroidRuntime:     at cn.****.activity.base.BaseActivity.getResources(BaseActivity.java:227)
        at me.jessyan.autosize.AutoSize.setDensity(AutoSize.java:244)
        at me.jessyan.autosize.AutoSize.autoConvertDensity(AutoSize.java:194)
        at me.jessyan.autosize.AutoSize.autoConvertDensityBaseOnWidth(AutoSize.java:123)
        at me.jessyan.autosize.AutoSize.autoConvertDensityOfGlobal(AutoSize.java:68)
        at *****.activity.base.BaseActivity.getResources(BaseActivity.java:227)

**Comment by JessYanCoding** [comment]
报错日志不全啊。。。

**Comment by Gseve** [comment]
大哥，都是循环着报错，报的都是我上传的，一样的。要我录屏么

**Comment by JessYanCoding** [comment]
是否录屏都不重要，关键是只报一个 AndroidRuntime 错误，具体什么错误也不知道，提出来我也无法解决问题

**Comment by Gseve** [comment]
2019-01-07 17:33:23.396 26804-26804/? E/AndroidRuntime:     at me.jessyan.autosize.AutoSize.autoConvertDensityBaseOnWidth(AutoSize.java:123)
        at me.jessyan.autosize.AutoSize.autoConvertDensityOfGlobal(AutoSize.java:68)
        at me.jessyan.autosize.demo.MainActivity.getResources(MainActivity.java:62)
        at me.jessyan.autosize.AutoSize.setDensity(AutoSize.java:244)
        at me.jessyan.autosize.AutoSize.autoConvertDensity(AutoSize.java:194)
        at me.jessyan.autosize.AutoSize.autoConvertDensityBaseOnWidth(AutoSize.java:123)
        at me.jessyan.autosize.AutoSize.autoConvertDensityOfGlobal(AutoSize.java:68)
        at me.jessyan.autosize.demo.MainActivity.getResources(MainActivity.java:62)
        at me.jessyan.autosize.AutoSize.setDensity(AutoSize.java:244)
        at me.jessyan.autosize.AutoSize.autoConvertDensity(AutoSize.java:194)
        at me.jessyan.autosize.AutoSize.autoConvertDensityBaseOnWidth(AutoSize.java:123)
        at me.jessyan.autosize.AutoSize.autoConvertDensityOfGlobal(AutoSize.java:68)
        at me.jessyan.autosize.demo.MainActivity.getResources(MainActivity.java:62)
        at me.jessyan.autosize.AutoSize.setDensity(AutoSize.java:244)
        at me.jessyan.autosize.AutoSize.autoConvertDensity(AutoSize.java:194)
        at me.jessyan.autosize.AutoSize.autoConvertDensityBaseOnWidth(AutoSize.java:123)
        at me.jessyan.autosize.AutoSize.autoConvertDensityOfGlobal(AutoSize.java:68)
        at me.jessyan.autosize.demo.MainActivity.getResources(MainActivity.java:62)
        at me.jessyan.autosize.AutoSize.setDensity(AutoSize.java:244)
        at me.jessyan.autosize.AutoSize.autoConvertDensity(AutoSize.java:194)
        at me.jessyan.autosize.AutoSize.autoConvertDensityBaseOnWidth(AutoSize.java:123)
        at me.jessyan.autosize.AutoSize.autoConvertDensityOfGlobal(AutoSize.java:68)
        at me.jessyan.autosize.demo.MainActivity.getResources(MainActivity.java:62)
        at me.jessyan.autosize.AutoSize.setDensity(AutoSize.java:244)
        at me.jessyan.autosize.AutoSize.autoConvertDensity(AutoSize.java:194)
        at me.jessyan.autosize.AutoSize.autoConvertDensityBaseOnWidth(AutoSize.java:123)
        at me.jessyan.autosize.AutoSize.autoConvertDensityOfGlobal(AutoSize.java:68)
        at me.jessyan.autosize.demo.MainActivity.getResources(MainActivity.java:62)
        at me.jessyan.autosize.AutoSize.setDensity(AutoSize.java:244)
        at me.jessyan.autosize.AutoSize.autoConvertDensity(AutoSize.java:194)
        at me.jessyan.autosize.AutoSize.autoConvertDensityBaseOnWidth(AutoSize.java:123)
        at me.jessyan.autosize.AutoSize.autoConvertDensityOfGlobal(AutoSize.java:68)
        at me.jessyan.autosize.demo.MainActivity.getResources(MainActivity.java:62)
        at me.jessyan.autosize.AutoSize.setDensity(AutoSize.java:244)
        at me.jessyan.autosize.AutoSize.autoConvertDensity(AutoSize.java:194)
        at me.jessyan.autosize.AutoSize.autoConvertDensityBaseOnWidth(AutoSize.java:123)
        at me.jessyan.autosize.AutoSize.autoConvertDensityOfGlobal(AutoSize.java:68)
        at me.jessyan.autosize.demo.MainActivity.getResources(MainActivity.java:62)
        at me.jessyan.autosize.AutoSize.setDensity(AutoSize.java:244)
        at me.jessyan.autosize.AutoSize.autoConvertDensity(AutoSize.java:194)
        at me.jessyan.autosize.AutoSize.autoConvertDensityBaseOnWidth(AutoSize.java:123)
        at me.jessyan.autosize.AutoSize.autoConvertDensityOfGlobal(AutoSize.java:68)
        at me.jessyan.autosize.demo.MainActivity.getResources(MainActivity.java:62)
        at me.jessyan.autosize.AutoSize.setDensity(AutoSize.java:244)
        at me.jessyan.autosize.AutoSize.autoConvertDensity(AutoSize.java:194)
        at me.jessyan.autosize.AutoSize.autoConvertDensityBaseOnWidth(AutoSize.java:123)
        at me.jessyan.autosize.AutoSize.autoConvertDensityOfGlobal(AutoSize.java:68)
        at me.jessyan.autosize.demo.MainActivity.getResources(MainActivity.java:62)
        at me.jessyan.autosize.AutoSize.setDensity(AutoSize.java:244)
        at me.jessyan.autosize.AutoSize.autoConvertDensity(AutoSize.java:194)
        at me.jessyan.autosize.AutoSize.autoConvertDensityBaseOnWidth(AutoSize.java:123)
        at me.jessyan.autosize.AutoSize.autoConvertDensityOfGlobal(AutoSize.java:68)
        at me.jessyan.autosize.demo.MainActivity.getResources(MainActivity.java:62)
        at me.jessyan.autosize.AutoSize.setDensity(AutoSize.java:244)

**Comment by Gseve** [comment]
这个问题你直接在demo中用模拟器试试不就知道了吗？

**Comment by JessYanCoding** [comment]
我的模拟器，没有复现

**Comment by Gseve** [comment]
大兄弟，我刚下载你的demo然后在MainActivity中加了@Override
public Resources getResources() {
    AutoSize.autoConvertDensityOfGlobal(this);
    return super.getResources();
}



然后在as自带的模拟器中运行，runtime crash一片
| |
古翔宇
|
|
erica3636@163.com
|
签名由网易邮箱大师定制


在2019年01月7日 17:44，JessYan<notifications@github.com> 写道：

我的模拟器，没有复现

**Comment by JessYanCoding** [comment]
找到问题了，oom 的问题，明天就发新版本解决

**Comment by xilost** [comment]
@JessYanCoding 三星note8也是同样的问题，等你的解决方案

**Comment by Gseve** [comment]
几点发版本，我给你测试下

**Comment by JessYanCoding** [comment]
@Gseve 下午吧，不确定，因为还有其他工作要做

**Comment by xilost** [comment]
@JessYanCoding 已经用上了，没有问题，辛苦了！
