### ISSUE TITLE
JessYan: 常见 Issues

### ISSUE THREAD

**Issue by JessYanCoding** [JessYanCoding/AndroidAutoSize#13]
* [当页面中有 WebView 时屏幕适配失效](https://github.com/JessYanCoding/AndroidAutoSize/issues/5)
* [AlertDialog 适配问题](https://github.com/JessYanCoding/AndroidAutoSize/issues/1)
* [单 Activity 多 Fragment 的适配问题](https://github.com/JessYanCoding/AndroidAutoSize/issues/3)

**Comment by MrLeeys** [comment]
在程序奔溃之后，原适配界面布局错乱

**Comment by QuincySx** [comment]
```Main2Activity Info: isBaseOnWidth = true, designWidthInDp = 360.000000, targetDensity = 3.000000, targetScaledDensity = 3.000000, targetDensityDpi = 480, targetXdpi = 3.000000```

布局
```
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".ui.Main2Activity">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="#FFFFFF"
        android:text="ssssdfdfd"
        android:textSize="16sp"
        android:textStyle="bold"
        android:textColor="#000000"
        app:layout_constraintBottom_toBottomOf="parent" />
</android.support.constraint.ConstraintLayout>
```

![image](https://user-images.githubusercontent.com/13297229/46092747-3032a900-c1e8-11e8-84aa-ef6faff23da0.png)

辨析率 1080 * 2220  5.3寸、在全民屏手机上也有这种问题

有一点不太明白，我是用的宽度适配，我布局设置高度设置为 match_parent 为什么底部有黑条呢

**Comment by hais1992** [comment]
![screenshot_2018-10-02-10-59-57-1015175296](https://user-images.githubusercontent.com/5223993/46327982-2e794300-c637-11e8-9fe6-4ba114558fa4.png)

求解，如何才能让系统以及一些第三方的控件、类库恢复正常。
换个方法问，就是怎样才能让这些控件展示出未使用AndroidAutoSize之前的样子。

**Comment by Inmortals** [comment]
我加了以后一点反应都没有啊很奇怪，没有适配。。

**Comment by QuincySx** [comment]
请单独开贴，按照模板填写，谢谢配合

**Comment by AresCool** [comment]
环境：AS3.2.1  ；JDK1.8； me.jessyan:autosize:1.0.5； build：3.2.1；ext.kotlin_version = '1.2.71'
编译不通过，直接报如下错误。有人遇到否？
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve me.jessyan:autosize:1.0.5.
Open File
Show Details


Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve me.jessyan:autosize:1.0.5.
Open File
Show Details


Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve me.jessyan:autosize:1.0.5.
Open File
Show Details


Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve me.jessyan:autosize:1.0.5.
Open File
Show Details


Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve me.jessyan:autosize:1.0.5.
Open File
Show Details

**Comment by JessYanCoding** [comment]
@AresCool 兄弟这种问题建议在群里询问，在这里询问会影响后面的朋友查找问题，而且这种问题是 Gradle 报的，基本和 AndroidAutoSize 没什么关系，可以在群里问问试试

**Comment by GeminiWy** [comment]
请问在不升级版本的情况下，这个问题有没有其他方案解决呢？FragmentManager.FragmentLifecycleCallbacks可以替换成其他的类吗？

**Comment by kofkoy123** [comment]
使用了您的适配，我发现以前我用的ImageView wrap_content属性的，点击按钮切换图片用代码setImageResource的时候会变小，我使用今日头条适配没有这个情况出现。麻烦帮忙看看

**Comment by JessYanCoding** [comment]
@kalasoo 看上面👆，实现 CancelAdapt 取消适配，并在 onCreate 直接使用 AutoSize#autoConvertDensity 适配，看是否有问题，是否使用的是副单位？开启新的 Issues 并完善截图等信息，然后回复我的问题，然后为了保持格式，这条留言会被删除

**Comment by zxcvluyang** [comment]
混淆

**Comment by xiaoxiaScut** [comment]
getResource#getDimensionPixelSize的值还是原先的，怎么破

**Comment by Gseve** [comment]
这个框架适配问题太多了。

**Comment by JessYanCoding** [comment]
@Gseve 有问题就提新 Issues，或者在 [意见收集区](https://github.com/JessYanCoding/AndroidAutoSize/issues/118) 中留言，上面已经写了这里只接受问题和解决方案的留言，其他留言都会被删除

**Comment by Gseve** [comment]
这个在小米8上，android9.0上会崩溃 
 @Override
    public Resources getResources() {
        AutoSize.autoConvertDensityOfGlobal(this); //如果没有自定义需求用这个方法
        AutoSize.autoConvertDensity(this, 667, false); //如果有自定义需求就用这个方法
        return super.getResources();
    }

**Comment by JessYanCoding** [comment]
@Gseve 兄弟，麻烦提新的 issues，错误日志，环境，版本信息按规则提供，上面已经说了只接受带有解决方案的留言，这么喜欢在这留言吗...

**Comment by Gseve** [comment]
嘿嘿

**Comment by love-311** [comment]
如果不想让 App 内的字体大小跟随系统设置中字体大小的改变，请调用 AutoSizeConfig.getInstance().setExcludeFontScale(true); 即可
不好意思想问一下这个地方，我在1.1.0～1.1.2版本上面都没有发现这个方法呢。。

**Comment by Gseve** [comment]
are you kidding me?你依赖工程的问题

**Comment by sinyu1012** [comment]
使用之后，toolbar 的 navigationicon 不居中

**Comment by 13849799704** [comment]
华为v8适配貌似没用。。黑鲨1代 vivo 基本都行 到了华为v8就显示不全了。。。变的特别大 怎么办？

**Comment by LJFDBXJ** [comment]
大哥，小弟已近走投无路，无奈选择这个框框，可是。。。。可是。。。。。我掉进了不可自拔的陷阱，这个框框就是BUG的集合体，为了解决适配，而使用适配，可是因为使用了适配，要解决一大堆适配，这哪是头条的适配方案，这是坑爹集团董事长的坑坑业务啊

**Comment by love-311** [comment]
> 大哥，小弟已近走投无路，无奈选择这个框框，可是。。。。可是。。。。。我掉进了不可自拔的陷阱，这个框框就是BUG的集合体，为了解决适配，而使用适配，可是因为使用了适配，要解决一大堆适配，这哪是头条的适配方案，这是坑爹集团董事长的坑坑业务啊

个人觉得本款适配方案算是比较简单也比较轻量级的吧，至于你说的关于使用这款适配之后造成了你自己之前适配的问题你这里没具体说明你之前的适配是依据怎样的原理实现的，所以我也不是很好说，另外你说这个框架是BUG集合体，感觉你也应该具体说明BUG在哪里啊。。

**Comment by LJFDBXJ** [comment]
@love-311 大神我可以加您微信吗，您帮帮帮我，我的微信935312568

**Comment by love-311** [comment]
> @love-311 大神我可以加您微信吗，您帮帮帮我，我的微信935312568

不是什么大神，我也帮不了你，框架我个人使用觉得还是挺不错的，所以多看看是不是自己的问题，另外看看自己对于这个框架是否理解到了吧~

**Comment by JessYanCoding** [comment]
@LJFDBXJ 兄弟，任何项目都不可能保证百分之百没有任何问题，即然是开源项目，那就是需要大家提出意见，以及指出问题所在，让大家都可以参与其中，这样才能保证开源项目能不断完善。

这个项目我本是出于自己的好意，贡献了这个项目，甚至连所有文档和注释，也是竭尽所能做的足够完善，我并没有收大家的任何好处，所以如果你觉得这个项目有任何问题，请指出问题所在，我会积极的去修复，但你没必要以 “BUG的集合体” 这种词汇来诋毁这个项目。

如果你觉得这个项目已经达到了 完全没法用 这个地步，你可以不用就是，去选择其他更完美的屏幕适配方案，这对我们没有任何影响。

任何开源项目作者，都只是出于自己的好意提供工具给大家使用，他并没有这个义务为大家提供服务，如果你觉得不好，你可以提意见，你也可以选择不使用。

**Comment by LJFDBXJ** [comment]
很抱歉，没有意识到我的用词态度，给您带来不便，辛苦了，有总比没有好，没有诋毁的意思，希望谅解，确实抱怨起不到任何作用，在这里向您表达我的歉意。不能@您了,显示您处于Busy状态。Thank you for your contribution

**Comment by swh001** [comment]
你好，请问下，加上之后为什么会卡顿，界面有个筛选吸顶的功能，然后自定义了个scrollView

**Comment by KobeBryant824** [comment]
我们设计的每个页面的 Width 是 750， Height 可能是变化的，有时1300+、有时1400+、有时1500+，有没有指定某个页面区别于默认的设置

**Comment by 1322202454** [comment]
如果是系统的CheckBox和RadioButton这样的按钮，右侧的图片如何让它显示成正常大小

**Comment by creativityingenuity** [comment]
> 坑爹集团董事长的坑坑业务

其实我也是这么觉得，三方库和有的手机简直无解

**Comment by M78Code** [comment]
项目是平板项目，UI图是1920px*1200px，横屏显示，所有的Activity都在清单文件中限制为横屏了，我在HUAWEI T1-823L平板上，一切正常，当屏幕进入熄屏状态后，再恢复，发现平板有一个由竖屏切换到横屏的过程，我的布局是ListView嵌套ListView，被嵌套的那层ListView的item布局，发现它适配失效了，这个有解决的参考吗

**Comment by jiaojiaozhe1** [comment]
什么时候支持androidX

**Comment by JessYanCoding** [comment]
@JasonYinH 一直都支持，框架做了 support 和  AndroidX 的 [兼容处理](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/autosize/src/main/java/me/jessyan/autosize/AutoSizeConfig.java#L164)，如果项目依赖 support 就使用 support，如果依赖 AndroidX 就使用 AndroidX

**Comment by chenfan1227** [comment]
在小米中的ListView 不管加啥 都会错位

**Comment by JessYanCoding** [comment]
@chenfan1227 https://github.com/JessYanCoding/AndroidAutoSize/issues/59#issuecomment-874488815

**Comment by billdizl** [comment]
main (native): tid=1 systid=20891 
#00 pc 0x4b4cc libc.so 
#01 pc 0x1af9c0 libart.so 
#02 pc 0x66a228 libart.so 
#03 pc 0x66a018 libart.so 
       at android.content.res.AssetManager.nativeGetResourceIdentifier(Native method)
       at android.content.res.AssetManager.getResourceIdentifier(AssetManager.java:791)
       at android.content.res.ResourcesImpl.getIdentifier(ResourcesImpl.java:281)
       at android.content.res.Resources.getIdentifier(Resources.java:2164)
       at me.jessyan.autosize.utils.ScreenUtils.getStatusBarHeight(ScreenUtils.java:43)
       at me.jessyan.autosize.AutoSizeConfig.init(AutoSizeConfig.java:250)
       at me.jessyan.autosize.AutoSizeConfig.init(AutoSizeConfig.java:205)
       at me.jessyan.autosize.InitProvider.onCreate(InitProvider.java:44)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
       at android.app.ActivityThread.installProvider(ActivityThread.java:7509)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7032)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6921)
       at android.app.ActivityThread.access$1600(ActivityThread.java:269)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:7959)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by xiaoxiaScut** [comment]
这是来自QQ邮箱的动回复邮件。
 
您好，你的邮件已成功接收。

**Comment by whyrookie** [comment]
感谢，usb插拔造成的适配失效，通过上面的方法得到解决

**Comment by xiaoxiaScut** [comment]
这是来自QQ邮箱的动回复邮件。
 
您好，你的邮件已成功接收。

**Comment by Vixb1122** [comment]
针对双屏异显，搞了个工具类替换 Presentation 后，可以使双屏异显支持该屏幕适配方案
相关 Issues：#188  #278  #393

Java 版本：[SecondaryDisplayHelper.java](https://gist.github.com/Vixb1122/b37ce7a5b9c6d05cfc6f9c534ea7906c#file-secondarydisplayhelper-java)
Kotlin 版本：[SecondaryDisplayHelper.kt](https://gist.github.com/Vixb1122/b37ce7a5b9c6d05cfc6f9c534ea7906c#file-secondarydisplayhelper-kt)

**Comment by xiaoxiaScut** [comment]
这是来自QQ邮箱的动回复邮件。
 
您好，你的邮件已成功接收。

**Comment by JessYanCoding** [comment]
[折叠屏、平行视窗、分屏及悬浮窗参考方案](https://blog.csdn.net/weixin_38702864/article/details/127071799?app_version=5.7.4&code=app_1562916241&csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22127071799%22%2C%22source%22%3A%22weixin_38702864%22%7D&uLinkId=usr1mkqgl919blen&utm_source=app)

**Comment by xiaoxiaScut** [comment]
这是来自QQ邮箱的动回复邮件。
 
您好，你的邮件已成功接收。

**Comment by billdizl** [comment]
我目前的项目是个老项目,我二月底集成了今日头条适配,上架到市场之后,引发了多个ANR,main (native): tid=1 systid=20891&nbsp;#00 pc 0x4b4cc libc.so&nbsp;
#01 pc 0x1af9c0 libart.so&nbsp;
#02 pc 0x66a228 libart.so&nbsp;
#03 pc 0x66a018 libart.so&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;at android.content.res.AssetManager.nativeGetResourceIdentifier(Native method)
&nbsp; &nbsp; &nbsp; &nbsp;at android.content.res.AssetManager.getResourceIdentifier(AssetManager.java:791)
&nbsp; &nbsp; &nbsp; &nbsp;at android.content.res.ResourcesImpl.getIdentifier(ResourcesImpl.java:281)
&nbsp; &nbsp; &nbsp; &nbsp;at android.content.res.Resources.getIdentifier(Resources.java:2164)
&nbsp; &nbsp; &nbsp; &nbsp;at me.jessyan.autosize.utils.ScreenUtils.getStatusBarHeight(ScreenUtils.java:43)
&nbsp; &nbsp; &nbsp; &nbsp;at me.jessyan.autosize.AutoSizeConfig.init(AutoSizeConfig.java:250)
&nbsp; &nbsp; &nbsp; &nbsp;at me.jessyan.autosize.AutoSizeConfig.init(AutoSizeConfig.java:205)
&nbsp; &nbsp; &nbsp; &nbsp;at me.jessyan.autosize.InitProvider.onCreate(InitProvider.java:44)
&nbsp; &nbsp; &nbsp; &nbsp;at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
&nbsp; &nbsp; &nbsp; &nbsp;at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
&nbsp; &nbsp; &nbsp; &nbsp;at android.app.ActivityThread.installProvider(ActivityThread.java:7509)
&nbsp; &nbsp; &nbsp; &nbsp;at android.app.ActivityThread.installContentProviders(ActivityThread.java:7032)
&nbsp; &nbsp; &nbsp; &nbsp;at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6921)
&nbsp; &nbsp; &nbsp; &nbsp;at android.app.ActivityThread.access$1600(ActivityThread.java:269)
&nbsp; &nbsp; &nbsp; &nbsp;at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
&nbsp; &nbsp; &nbsp; &nbsp;at android.os.Handler.dispatchMessage(Handler.java:106)
&nbsp; &nbsp; &nbsp; &nbsp;at android.os.Looper.loop(Looper.java:233)
&nbsp; &nbsp; &nbsp; &nbsp;at android.app.ActivityThread.main(ActivityThread.java:7959)
&nbsp; &nbsp; &nbsp; &nbsp;at java.lang.reflect.Method.invoke(Native method)
&nbsp; &nbsp; &nbsp; &nbsp;at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
&nbsp; &nbsp; &nbsp; &nbsp;at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
这个是直接报今日头条适配的ANR错误
还有报
main (native): tid=1 systid=22251&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;at libcore.io.Linux.access(Native method)
&nbsp; &nbsp; &nbsp; &nbsp;at libcore.io.ForwardingOs.access(ForwardingOs.java:72)
&nbsp; &nbsp; &nbsp; &nbsp;at libcore.io.BlockGuardOs.access(BlockGuardOs.java:73)
&nbsp; &nbsp; &nbsp; &nbsp;at libcore.io.ForwardingOs.access(ForwardingOs.java:72)
&nbsp; &nbsp; &nbsp; &nbsp;at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7839)
&nbsp; &nbsp; &nbsp; &nbsp;at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
&nbsp; &nbsp; &nbsp; &nbsp;at java.io.File.exists(File.java:815)
&nbsp; &nbsp; &nbsp; &nbsp;at android.app.ContextImpl.ensureExternalDirsExistOrFilter(ContextImpl.java:2875)
&nbsp; &nbsp; &nbsp; &nbsp;at android.app.ContextImpl.getExternalCacheDirs(ContextImpl.java:825)
&nbsp; &nbsp; &nbsp; &nbsp;at android.content.ContextWrapper.getExternalCacheDirs(ContextWrapper.java:308)
&nbsp; &nbsp; &nbsp; &nbsp;at androidx.core.content.ContextCompat.getExternalCacheDirs(ContextCompat.java:434)
&nbsp; &nbsp; &nbsp; &nbsp;at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:696)
&nbsp; &nbsp; &nbsp; &nbsp;at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:635)
&nbsp; &nbsp; &nbsp; &nbsp;at androidx.core.content.FileProvider.attachInfo(FileProvider.java:416)
&nbsp; &nbsp; &nbsp; &nbsp;at android.app.ActivityThread.installProvider(ActivityThread.java:7524)
&nbsp; &nbsp; &nbsp; &nbsp;at android.app.ActivityThread.installContentProviders(ActivityThread.java:7024)
&nbsp; &nbsp; &nbsp; &nbsp;at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6937)
&nbsp; &nbsp; &nbsp; &nbsp;at android.app.ActivityThread.access$1300(ActivityThread.java:263)
&nbsp; &nbsp; &nbsp; &nbsp;at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1991)
&nbsp; &nbsp; &nbsp; &nbsp;at android.os.Handler.dispatchMessage(Handler.java:106)
&nbsp; &nbsp; &nbsp; &nbsp;at android.os.Looper.loop(Looper.java:240)
&nbsp; &nbsp; &nbsp; &nbsp;at android.app.ActivityThread.main(ActivityThread.java:8000)
&nbsp; &nbsp; &nbsp; &nbsp;at java.lang.reflect.Method.invoke(Native method)
&nbsp; &nbsp; &nbsp; &nbsp;at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
&nbsp; &nbsp; &nbsp; &nbsp;at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)





经过研究发现&nbsp; 这两个问题是同属于同一问题导致,具体是由 今日头条的InitProvider.java:44 引发




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月28日(星期一) 晚上6:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JessYanCoding/AndroidAutoSize] JessYan: 今日头条屏幕适配方案常见问题汇总，提问前必看！ (#13)





 这是来自QQ邮箱的动回复邮件。
 &nbsp;
 您好，你的邮件已成功接收。

**Comment by zhangchuanchuan** [comment]
某些版本的Android11和Android12以后。会存在如下问题：
1. APP进入页面A（竖屏）
2. 点击“跳转页面B”进入页面B（横屏）
3. 返回页面A
4. 点击“弹窗”，弹窗C出现。弹窗出现以后：此时ResourcesImpl的updateConfiguration函数被调用了。
mMetrics.setTo(metrics)，resource的metrics被系统修改回默认值了。
5. 关闭弹窗C，再次点击“弹窗”。显示异常。

**Comment by xiaoxiaScut** [comment]
这是来自QQ邮箱的动回复邮件。
 
您好，你的邮件已成功接收。

**Comment by jokerrou** [comment]
> [折叠屏、平行视窗、分屏及悬浮窗参考方案](https://blog.csdn.net/weixin_38702864/article/details/127071799?app_version=5.7.4&code=app_1562916241&csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22127071799%22%2C%22source%22%3A%22weixin_38702864%22%7D&uLinkId=usr1mkqgl919blen&utm_source=app)

这个链接并没有解决什么问题，折叠屏在平行视窗的情况下设置的density与实际的并不一样，猜测在这种情况下可能是系统篡改了density，怎么解决呢？

**Comment by xiaoxiaScut** [comment]
这是来自QQ邮箱的动回复邮件。
 
您好，你的邮件已成功接收。

**Comment by jokerrou** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Xxj-star** [comment]
你这个问题可以解决 但是加上override fun getResources(): Resources {
AutoSizeCompat.autoConvertDensityOfGlobal(super.getResources()) //如果没有自定义需求用这个方法
return super.getResources()
}之后 对于三星SM-A166U1型号手机无法弹出软件盘 原理是因为三星厂家输入法管理系统可能依赖于原始的Resources配置来正确定位和显示软键盘，当Resources被修改后，三星的输入法管理系统无法正确识别输入框的位置或焦点状态，去掉就正常弹出 不信你可以试下三星手机

**Comment by xiaoxiaScut** [comment]
这是来自QQ邮箱的动回复邮件。
 
您好，你的邮件已成功接收。

**Comment by jokerrou** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
