### ISSUE TITLE
使用autoConvertDensityOfGlobal出现的crash，不必现。

### ISSUE THREAD

**Issue by xilost** [JessYanCoding/AndroidAutoSize#168]
- [x] Autosize Version: v1.1.2
- [x] Target Android Version: Android 9.0 
- [x] Device Model: SM-G9650
- [x] Device Resolution: 2960 * 1440
- [x] Design Size On AndroidManifest: 375dp * 667dp

友盟统计捕获的bug，Log日志如下：

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.weibo.wbalk/com.weibo.wbalk.mvp.ui.activity.MainTabActivity}: java.lang.IllegalArgumentException: you must set design_width_in_dp in your AndroidManifest file
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3086)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:6981)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
Caused by: java.lang.IllegalArgumentException: you must set design_width_in_dp in your AndroidManifest file
    at me.jessyan.autosize.utils.Preconditions.checkArgument(Preconditions.java:39)
    at me.jessyan.autosize.AutoSizeConfig.getDesignWidthInDp(AutoSizeConfig.java:432)
    at me.jessyan.autosize.AutoSizeCompat.autoConvertDensityOfGlobal(AutoSizeCompat.java:54)
    at com.weibo.wbalk.mvp.ui.activity.MainTabActivity.getResources(MainTabActivity.java:543)
    at android.view.Window.getDefaultFeatures(Window.java:1704)
    at android.view.Window.<init>(Window.java:671)
    at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:343)
    at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:352)
    at android.app.Activity.attach(Activity.java:7245)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3033)
    ... 11 more
java.lang.IllegalArgumentException: you must set design_width_in_dp in your AndroidManifest file
    at me.jessyan.autosize.utils.Preconditions.checkArgument(Preconditions.java:39)
    at me.jessyan.autosize.AutoSizeConfig.getDesignWidthInDp(AutoSizeConfig.java:432)
    at me.jessyan.autosize.AutoSizeCompat.autoConvertDensityOfGlobal(AutoSizeCompat.java:54)
    at com.weibo.wbalk.mvp.ui.activity.MainTabActivity.getResources(MainTabActivity.java:543)
    at android.view.Window.getDefaultFeatures(Window.java:1704)
    at android.view.Window.<init>(Window.java:671)
    at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:343)
    at com.android.internal.policy.PhoneWindow.<init>(PhoneWindow.java:352)
    at android.app.Activity.attach(Activity.java:7245)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3033)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3229)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:6981)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

**Comment by StandOpen** [comment]
我也遇到了这个问题，打开另外一个进程的页面，适配失效，使用这个方法直接崩溃

**Comment by lujianzhao** [comment]
我也遇见了，新进程就会出现问题。。

**Comment by itgoyo** [comment]
我这边也是接入第三方 SDK，打开第三方的页面就遇到了
```
java.lang.IllegalArgumentException: you must set design_width_in_dp  in your AndroidManifest file
```

**Comment by erichyx** [comment]
我集成阿里热修复，每次一启动就出现这个错误。

**Comment by ZhanRu** [comment]
--------- beginning of crash
08-09 15:18:21.051  3858  3858 E AndroidRuntime: FATAL EXCEPTION: main
08-09 15:18:21.051  3858  3858 E AndroidRuntime: Process: com.zkzz.app.user:error_activity, PID: 3858
08-09 15:18:21.051  3858  3858 E AndroidRuntime: java.lang.IllegalArgumentException: you must set design_width_in_dp  in your AndroidManifest file
08-09 15:18:21.051  3858  3858 E AndroidRuntime: at me.jessyan.autosize.utils.Preconditions.checkArgument(Preconditions.java:39)
08-09 15:18:21.051  3858  3858 E AndroidRuntime: at me.jessyan.autosize.AutoSizeConfig.getDesignWidthInDp(AutoSizeConfig.java:432)
08-09 15:18:21.051  3858  3858 E AndroidRuntime: at me.jessyan.autosize.AutoSizeCompat.autoConvertDensityOfGlobal(AutoSizeCompat.java:54)
08-09 15:18:21.051  3858  3858 E AndroidRuntime: at com.zkzz.module.base.view.customdialoglib.CustomDialog.show(CustomDialog.java:188)
08-09 15:18:21.051  3858  3858 E AndroidRuntime: at com.zkzz.app.user.base.UserApplication.showUpdateDialog(UserApplication.java:178)
08-09 15:18:21.051  3858  3858 E AndroidRuntime: at com.zkzz.app.user.base.UserApplication.onFinished(UserApplication.java:151)
08-09 15:18:21.051  3858  3858 E AndroidRuntime: at com.zkzz.app.user.ota.OtaManager$MyDownloadListener.onFinished(OtaManager.java:459)
08-09 15:18:21.051  3858  3858 E AndroidRuntime: at com.baidu.otaplugin.commands.f.a(DownloadCmd.java:220)
08-09 15:18:21.051  3858  3858 E AndroidRuntime: at com.baidu.otaplugin.commands.OtaCommand$2.run(OtaCommand.java:156)
08-09 15:18:21.051  3858  3858 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:836)
08-09 15:18:21.051  3858  3858 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:103)
08-09 15:18:21.051  3858  3858 E AndroidRuntime: at android.os.Looper.loop(Looper.java:203)
08-09 15:18:21.051  3858  3858 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6337)
08-09 15:18:21.051  3858  3858 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
08-09 15:18:21.051  3858  3858 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
08-09 15:18:21.051  3858  3858 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
08-09 15:18:21.052   319   319 I DisplayDevice: [Built-in Screen (type:0)] fps:0.996242,dur:1003.77,max:1003.77,min:1003.77
08-09 15:18:21.069   817  1387 V PackageManager: getPackageInfo com.zkzz.app.user: Package{123978e com.zkzz.app.user}
08-09 15:18:21.098   817  4444 D AES     : onEndOfErrorDumpThread: system_app_crash Process: com.zkzz.app.user:error_activity
08-09 15:18:21.098   817  4444 D AES     : Flags: 0x38c8be45
08-09 15:18:21.098   817  4444 D AES     : Package: com.zkzz.app.user v14 (0.1.4)
08-09 15:18:21.098   817  4444 D AES     : Foreground: No
08-09 15:18:21.098   817  4444 D AES     : Build: alps/full_aeon6739_36_n1/Android/1564741487:user/test-keys
08-09 15:18:21.098   817  4444 D AES     : 
08-09 15:18:21.098   817  4444 D AES     : java.lang.IllegalArgumentException: you must set design_width_in_dp  in your AndroidManifest file
08-09 15:18:21.098   817  4444 D AES     : at me.jessyan.autosize.utils.Preconditions.checkArgument(Preconditions.java:39)
08-09 15:18:21.098   817  4444 D AES     : at me.jessyan.autosize.AutoSizeConfig.getDesignWidthInDp(AutoSizeConfig.java:432)
08-09 15:18:21.098   817  4444 D AES     : at me.jessyan.autosize.AutoSizeCompat.autoConvertDensityOfGlobal(AutoSizeCompat.java:54)
08-09 15:18:21.098   817  4444 D AES     : at com.zkzz.module.base.view.customdialoglib.CustomDialog.show(CustomDialog.java:188)
08-09 15:18:21.098   817  4444 D AES     : at com.zkzz.app.user.base.UserApplication.showUpdateDialog(UserApplication.java:178)
08-09 15:18:21.098   817  4444 D AES     : at com.zkzz.app.user.base.UserApplication.onFinished(UserApplication.java:151)
08-09 15:18:21.098   817  4444 D AES     : at com.zkzz.app.user.ota.OtaManager$MyDownloadListener.onFinished(OtaManager.java:459)
08-09 15:18:21.098   817  4444 D AES     : at com.baidu.otaplugin.commands.f.a(DownloadCmd.java:220)
08-09 15:18:21.098   817  4444 D AES     : at com.baidu.otaplugin.commands.OtaCommand$2.run(OtaCommand.java:156)
08-09 15:18:21.098   817  4444 D AES     : at android.os.Handler.handleCallback(Handler.java:836)
08-09 15:18:21.098   817  4444 D AES     : at android.os.Handler.dispatchMessage(Handler.java:103)
08-09 15:18:21.098   817  4444 D AES     : at android.os.Looper.loop(Looper.java:203)
08-09 15:18:21.098   817  4444 D AES     : at android.app.ActivityThread.main(ActivityThread.java:6337)
08-09 15:18:21.098   817  4444 D AES     : at java.lang.reflect.Method.invoke(Native Method)
08-09 15:18:21.098   817  4444 D AES     : at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084)
08-09 15:18:21.098   817  4444 D AES     : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945)
08-09 15:18:21.098   817  4444 D AES     :  3858
08-09 15:18:21.098   817  4444 W AES     : Exception Log handling...

我也出现了

**Comment by JessYanCoding** [comment]
在 Application#onCreate 中手动设置下 setDesignWidthInDp

**Comment by JessYanCoding** [comment]
多个进程需要使用 AutoSize.initCompatMultiProcess(this); 
 https://github.com/JessYanCoding/AndroidAutoSize/blob/master/demo/src/main/java/me/jessyan/autosize/demo/BaseApplication.java#L57
