### ISSUE TITLE
运行打开崩溃

### ISSUE THREAD

**Issue by AfterChristmas** [JessYanCoding/AndroidAutoSize#189]
### Environment
- [x] Autosize Version: 1.1.2
- [x] Target Android Version: Android4.3
- [x] Device Model: huawei s8-701
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 360*640

### Log:

```log
java.lang.NoSuchMethodError: android.support.v4.app.FragmentManager$FragmentLifecycleCallbacks.<init>
        at me.jessyan.autosize.FragmentLifecycleCallbacksImpl.<init>(FragmentLifecycleCallbacksImpl.java:38)
        at me.jessyan.autosize.ActivityLifecycleCallbacksImpl.<init>(ActivityLifecycleCallbacksImpl.java:45)
        at me.jessyan.autosize.AutoSizeConfig.init(AutoSizeConfig.java:237)
        at me.jessyan.autosize.AutoSizeConfig.init(AutoSizeConfig.java:174)
        at me.jessyan.autosize.InitProvider.onCreate(InitProvider.java:37)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1214)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1189)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5170)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4769)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4709)
        at android.app.ActivityThread.access$1600(ActivityThread.java:148)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5457)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:879)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:695)
        at dalvik.system.NativeStart.main(Native Method)

```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/issues/32
