### ISSUE TITLE
导入后运行项目报运行时异常，指向 jessyan.autosize.initprovider文件

### ISSUE THREAD

**Issue by SmithYim** [JessYanCoding/AndroidAutoSize#192]
java.lang.RuntimeException: Unable to get provider me.jessyan.autosize.InitProvider: java.lang.NullPointerException: application == null
        at android.app.ActivityThread.installProvider(ActivityThread.java:5672)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5242)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5182)
        at android.app.ActivityThread.-wrap3(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5975)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
     Caused by: java.lang.NullPointerException: application == null
        at me.jessyan.autosize.utils.Preconditions.checkNotNull(Preconditions.java:77)
        at me.jessyan.autosize.AutoSizeConfig.init(AutoSizeConfig.java:198)
        at me.jessyan.autosize.AutoSizeConfig.init(AutoSizeConfig.java:174)
        at me.jessyan.autosize.InitProvider.onCreate(InitProvider.java:37)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1801)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1776)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5669)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5242) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5182) 
        at android.app.ActivityThread.-wrap3(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:5975) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by SmithYim** [comment]
根据文档进行了initCompatMultiProcess方法调用还是报错，实在不知道该怎么解决了

**Comment by JessYanCoding** [comment]
报错是因为，在用于框架初始化的 initprovider 中调用 getContext().getApplicationContext() 返回的是 null，按理说不会返回 null，我这里也是正常的，你可以断点看下是不是返回的空
