### ISSUE TITLE
某机型运行打开崩溃

### ISSUE THREAD

**Issue by erichyx** [JessYanCoding/AndroidAutoSize#210]
### Environment
- [x] Autosize Version: 1.1.2
- [x] Target Android Version: Android 7.1.1
- [x] Device Model: Mi Note 3
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 360dp * 640dp

### Log:
```
java.lang.ArrayIndexOutOfBoundsException: src.length=2 srcPos=1 dst.length=34 dstPos=25 length=2
    at java.lang.System.arraycopy(System.java:458)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:551)
    at java.lang.StringBuilder.append(StringBuilder.java:205)
    at java.lang.StringBuilder.append(StringBuilder.java:204)
    at java.lang.FloatingDecimal.appendTo(FloatingDecimal.java:1017)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:679)
    at java.lang.StringBuilder.append(StringBuilder.java:230)
    at me.jessyan.autosize.AutoSizeCompat.autoConvertDensity(AutoSizeCompat.java)
    at me.jessyan.autosize.AutoSizeCompat.autoConvertDensityBaseOnWidth(AutoSizeCompat.java)
    at me.jessyan.autosize.AutoSizeCompat.autoConvertDensityOfGlobal(AutoSizeCompat.java)
    at com.matt.b.b.getResources(BaseActivity.kt)
    at android.content.Context.getColor(Context.java:517)
    at androidx.core.content.b.a(ContextCompat.java)
    at com.matt.modules.home.HomeFragment.a(HomeFragment.kt)
    at com.matt.modules.home.HomeFragment.a(HomeFragment.kt)
    at com.matt.modules.home.HomeFragment.a(HomeFragment.kt)
    at com.matt.modules.home.i.a(HomeFragment.kt)
```

**Comment by JessYanCoding** [comment]
没显示在 me.jessyan.autosize.AutoSizeCompat.autoConvertDensity 多少行报错？这个类里没用到过StringBuilder 啊
