### ISSUE TITLE
1.1.2升级到1.2.1重写getResources后，进入带webView的页面直接崩溃

### ISSUE THREAD

**Issue by oOJohn6Oo** [JessYanCoding/AndroidAutoSize#282]
#31 # Environment
- [x] Autosize Version: v1.2.1
- [x] Target Android Version: Android 8.1
- [x] Device Model: Smartisan R1
- [x] Device Resolution: 6.17 inch, 2242x1080 pixel(403ppi)
- [x] Design Size On AndroidManifest: 1024dp based on width

### Log:
```log
2020-03-24 09:58:55.416 E/AndroidRuntime: FATAL EXCEPTION: Thread-13
    Process: com.venpoo.android.musicscore, PID: 19702
    java.lang.IllegalStateException: Not in applications main thread
        at me.jessyan.autosize.utils.Preconditions.checkMainThread(Preconditions.java:113)
        at me.jessyan.autosize.AutoSizeCompat.autoConvertDensity(AutoSizeCompat.java:139)
        at me.jessyan.autosize.AutoSizeCompat.autoConvertDensityBaseOnWidth(AutoSizeCompat.java:112)
        at me.jessyan.autosize.AutoSizeCompat.autoConvertDensityOfGlobal(AutoSizeCompat.java:57)
        at com.xxx.android.xxx.base.BaseActivity.getResources(BaseActivity.kt:154)
        at android.content.ContextWrapper.getResources(ContextWrapper.java:89)
        at org.chromium.base.smartisan.DeviceInfo.<init>(DeviceInfo.java:74)
        at org.chromium.android_webview.smartisan.data_report.Toutiao$1.run(Toutiao.java:41)
        at java.lang.Thread.run(Thread.java:764)
```

### Screenshot
调出带webview的fragment直接崩溃
### Related Code:
```java
      override fun getResources(): Resources {
        AutoSizeCompat.autoConvertDensityOfGlobal(super.getResources())
        return super.getResources()
    }

```

### Others:
看了下1.2.1增加了主线程检测？请问这个怎么解决？

**Comment by oOJohn6Oo** [comment]
哦，对了，我项目中用了JetPack Navigation，使用这个切换fragment的

**Comment by JessYanCoding** [comment]
自己切换到主线程执行啊

**Comment by oOJohn6Oo** [comment]
> 自己判断非主线的时候，自己切换到主线程执行这段代码啊

搞定了，感谢，目前没发现什么影响。
