### ISSUE TITLE
导入包后 报错 Class

### ISSUE THREAD

**Issue by silentcmz** [JessYanCoding/AndroidAutoSize#34]
### Environment
- [x] Autosize Version: 0.9.1
- [x] Target Android Version: 22
- [x] Device Model: 联想pad
- [x] Device Resolution: 1080*1920
- [x] Design Size On AndroidManifest: 

### Log:

```log
java.lang.NoClassDefFoundError: me.jessyan.autosize.FragmentLifecycleCallbacksImpl
        at me.jessyan.autosize.ActivityLifecycleCallbacksImpl.<init>(ActivityLifecycleCallbacksImpl.java:45)
        at me.jessyan.autosize.AutoSizeConfig.init(AutoSizeConfig.java:206)
        at me.jessyan.autosize.AutoSizeConfig.init(AutoSizeConfig.java:146)
        at me.jessyan.autosize.InitProvider.onCreate(InitProvider.java:37)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1801)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1776)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5427)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5000)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4940)
        at android.app.ActivityThread.-wrap1(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1549)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5728)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

```

### Related Code:
```java
  

```

**Comment by silentcmz** [comment]
导入后 运行就报错
