### ISSUE TITLE
当meta-data的值有小数点时会类型转换错误崩溃

### ISSUE THREAD

**Issue by cikichen** [JessYanCoding/AndroidAutoSize#361]
### Log:

```log
2021-07-01 10:18:53.219 19473-19500/com.p E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: cp, PID: 19473
    java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
        at me.jessyan.autosize.AutoSizeConfig$2.run(AutoSizeConfig.java:702)
        at java.lang.Thread.run(Thread.java:919)
2021-07-01 10:18:53.227 19473-19503/cp E/Perf: Fail to get file list cp
2021-07-01 10:18:53.228 19473-19503/cp E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2021-07-01 10:18:53.228 19473-19503/cp E/Perf: Fail to get file list cp
2021-07-01 10:18:53.228 19473-19503/cp E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2021-07-01 10:18:53.229 19473-19503/cp E/Perf: Fail to get file list oat

```

```
        <meta-data
            android:name="design_width_in_dp"
            android:value="667.5"/>
        <meta-data
            android:name="design_height_in_dp"
            android:value="375.5"/>
```

特殊情况会出现这种设计图，然后会崩溃，去掉小树部分就没问题了

**Comment by JessYanCoding** [comment]
AndroidManifest 不支持小数点，想用小数点，就不填写 meta-data，在初始化时自己调用 [setDesignWidthInDp](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/autosize/src/main/java/me/jessyan/autosize/AutoSizeConfig.java#L650)
