### ISSUE TITLE
ANR

### ISSUE THREAD

**Issue by billdizl** [JessYanCoding/AndroidAutoSize#395]
main (native): tid=1 systid=20891 
#00 pc 0x4b4cc libc.so 
#01 pc 0x1af9c0 libart.so 
#02 pc 0x66a228 libart.so 
#03 pc 0x66a018 libart.so 
       at android.content.res.AssetManager.nativeGetResourceIdentifier(Native method)
       at android.content.res.AssetManager.getResourceIdentifier(AssetManager.java:791)
       at android.content.res.ResourcesImpl.getIdentifier(ResourcesImpl.java:281)
       at android.content.res.Resources.getIdentifier(Resources.java:2164)
       at me.jessyan.autosize.utils.ScreenUtils.getStatusBarHeight(ScreenUtils.java:43)
       at me.jessyan.autosize.AutoSizeConfig.init(AutoSizeConfig.java:250)
       at me.jessyan.autosize.AutoSizeConfig.init(AutoSizeConfig.java:205)
       at me.jessyan.autosize.InitProvider.onCreate(InitProvider.java:44)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
       at android.app.ActivityThread.installProvider(ActivityThread.java:7509)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7032)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6921)
       at android.app.ActivityThread.access$1600(ActivityThread.java:269)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:233)
       at android.app.ActivityThread.main(ActivityThread.java:7959)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

机型信息:
设备
品牌：OnePlus
型号：OnePlus 8 5G
屏幕方向： 未知
可用 RAM： Unknown
可用磁盘空间： Unknown
操作系统
版本：Android 11
屏幕方向： 未知
是否已取得 root 权限：否
ANR
日期：2022年3月26日 22:39:06

**Comment by JessYanCoding** [comment]
报错日志，只是指出了当框架初始化时调用系统的 Resources#getIdentifier 方法报了错，但是没看到报错类型，也不知道是什么原因导致的报错，难道是 One Plus 的系统把 status_bar_height 干掉了，或者不允许调用 status_bar_height？你确定日志是否是全的？

https://github.com/JessYanCoding/AndroidAutoSize/issues/249 使用这个方法，自己控制初始化，并在初始化的时候 try catch 看是否能解决
