### ISSUE TITLE
华为10.0设备crash

### ISSUE THREAD

**Issue by lvxinghe** [JessYanCoding/AndroidAutoSize#400]
华为平板启动activity闪退

java.lang.IllegalArgumentException: lightY must be finite, given=NaN
        at android.graphics.HardwareRenderer.validateFinite(HardwareRenderer.java:855)
        at android.graphics.HardwareRenderer.setLightSourceGeometry(HardwareRenderer.java:227)
        at android.view.ThreadedRenderer.setLightCenter(ThreadedRenderer.java:510)
        at android.view.ThreadedRenderer.setup(ThreadedRenderer.java:496)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2748)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1879)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8170)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
        at android.view.Choreographer.doCallbacks(Choreographer.java:875)
        at android.view.Choreographer.doFrame(Choreographer.java:776)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**Comment by JessYanCoding** [comment]
报错信息里面没有指向框架的信息，框架没有用到报错信息里相关的 API

**Comment by JessYanCoding** [comment]
试试不引用框架只是复制 [这个方法里的代码](https://github.com/JessYanCoding/AndroidAutoSize/blob/master/autosize/src/main/java/me/jessyan/autosize/AutoSize.java#L288) ，看看调用这个方法时是否会报错，如果报错说明华为原生不支持，如果不报错，在引用框架断点看看哪里报的错

**Comment by wys619** [comment]
同样遇到类似问题，我们上个版本尝试接入了这个框架，然后就崩溃率飙升，bugly的堆栈信息如下：

```
#105319 java.lang.IllegalArgumentException
lightZ must be a finite positive, given=-719.99994
android.graphics.HardwareRenderer.validatePositive(HardwareRenderer.java:1038)
android.graphics.HardwareRenderer.setLightSourceGeometry(HardwareRenderer.java:259)
android.view.ThreadedRenderer.setLightCenter(ThreadedRenderer.java:656)
android.view.ThreadedRenderer.setup(ThreadedRenderer.java:572)
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4063)
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2895)
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10515)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1760)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1769)
android.view.Choreographer.doCallbacks(Choreographer.java:1273)
android.view.Choreographer.doFrame(Choreographer.java:1140)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1743)
android.os.Handler.handleCallback(Handler.java:1013)
android.os.Handler.dispatchMessage(Handler.java:101)
android.os.Looper.loopOnce(Looper.java:226)
android.os.Looper.loop(Looper.java:328)
android.app.ActivityThread.main(ActivityThread.java:9231)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
```

发生这个问题的机型不仅有华为，小米、OPPO、vivo都有，而且覆盖Android 系统的10、11、12、13、14版本

移除之后重新发布，该异常消失，原因暂不明确；
