### ISSUE TITLE
Please call the AutoSizeConfig#init() first

### ISSUE THREAD

**Issue by zhengdong1201** [JessYanCoding/AndroidAutoSize#46]
### Environment
- [x] Autosize Version: 
- [x] Target Android Version: 
- [x] Device Model: 
- [x] Device Resolution: 
- [x] Design Size On AndroidManifest: 

### Log:

```log
  java.lang.RuntimeException: Unable to create application com.crest.crest_parent.application.MyApplication: java.lang.NullPointerException: Please call the AutoSizeConfig#init() first
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
        at android.app.ActivityThread.-wrap1(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.NullPointerException: Please call the AutoSizeConfig#init() first
        at me.jessyan.autosize.utils.Preconditions.checkNotNull(Preconditions.java:77)
        at me.jessyan.autosize.AutoSizeConfig.setAutoAdaptStrategy(AutoSizeConfig.java:247)
        at com.crest.crest_parent.application.MyApplication.initAutoSizeConfig(MyApplication.java:179)
        at com.crest.crest_parent.application.MyApplication.onCreate(MyApplication.java:70)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
        at android.app.ActivityThread.-wrap1(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

```

### Related Code:
```java
  

```

**Comment by JessYanCoding** [comment]
？
