### ISSUE TITLE
HUAWEI 平板已启动就闪退！！

### ISSUE THREAD

**Issue by 429329513wanting** [JessYanCoding/AndroidAutoSize#70]
Android版本4.4.4
 
java.lang.RuntimeException: Unable to get provider me.jessyan.autosize.InitProvider: java.lang.ClassNotFoundException: Didn't find class "me.jessyan.autosize.InitProvider" on path: DexPathList[[zip file "/data/app/com.sendinfo.renthouse-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.sendinfo.renthouse-2, /vendor/lib, /data/cust/lib, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:5093)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4679)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4619)
        at android.app.ActivityThread.access$1800(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1301)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5342)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)

**Comment by JessYanCoding** [comment]
4.4 分包问题，参考 **MVPArms** 的 [解决方案](https://github.com/JessYanCoding/MVPArms/wiki/Issues#3)

**Comment by JessYanCoding** [comment]
https://github.com/JessYanCoding/AndroidAutoSize/commit/5a8bfa97039ec4568557a02ff25cd9169591d74d
